# hard_tabs = true
unstable_features = true
condense_wildcard_suffixes = true
enum_discrim_align_threshold = 20
struct_field_align_threshold = 20
fn_single_line = true
format_code_in_doc_comments = true
format_strings = true
imports_granularity = "Crate"
reorder_impl_items = true
group_imports = "StdExternalCrate"
report_fixme = "Always"
report_todo = "Always"
use_field_init_shorthand = true
wrap_comments = true
